$FirebaseSDKVersion = '7.11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'rollbox' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'Share' do
  pod 'Firebase/Auth'
  pod 'SwiftSVG', '~> 2.3.0'
  pod 'Alamofire', '~> 5.2'
end

target 'ImageNotification' do
  pod 'Firebase/Messaging', '~> 7.11.0' # eg 6.31.0
end

