name: Build And Deploy App To Firebase Distribution Prod

on:
  push:
    branches:
      - 'PROD/*'
      - '!PROD/last'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.3'
      - uses: c-hive/gha-yarn-cache@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install node modules
        run: yarn install
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/android/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/android/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-caches-
      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew
      - name: Build assembleRelease
        run: cd android && ./gradlew bundleRelease --no-daemon
      - name: Sign App Bundle
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_BASE_PROD}}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS_PROD }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD_PROD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD_PROD }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed App Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID_PROD}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: ${{secrets.FIREBASE_GROUPS_PROD}}
          file: ${{steps.sign_app.outputs.signedReleaseFile}}
          releaseNotesFile: ./releaseNotesFile.txt
